// Import the createSlice function from @reduxjs/toolkit, which is used to create a slice of the Redux state.
// The createSlice function takes an options object with the following properties: name, initialState, reducers.
import { createSlice, nanoid } from "@reduxjs/toolkit";

// Define the initial state of the slice, which is an object with a single property 'list' that is an empty array.
// The state is the current state of the application, which is stored in the Redux store.
const firstState = {
    // The list property is an array that will store the todo items.
    list: []
}

// Create a slice of the Redux state using the createSlice function.
// The createSlice function returns an object with the following properties: actions, reducer.
const Slice = createSlice({
    // The name property is a string that identifies the slice.
    name: 'firstState',
    // The initialState property is the initial state of the slice.
    initialState: firstState,
    // The reducers property is an object that defines the reducers for the slice.
    // A reducer is a function that takes the current state and an action, and returns a new state.
    reducers: {
        // The addTodo reducer adds a new todo item to the list.
        addTodo: (state: any, action: { payload: { taskName: string } }) => {
            // The state is the current state of the slice, which is an object with a single property 'list'.
            // The action is an object that contains the payload of the action, which is the new todo item.
            console.log(action)
            const task = {
                // The id property is a unique identifier for the todo item, which is generated using the nanoid function.
                // The nanoid function generates a random string that is unique for each todo item.
                id: nanoid(),
                // The taskName property is the name of the todo item, which is contained in the action payload.
                taskName: action.payload.taskName
            }
            // The state.list.push(task) statement adds the new todo item to the list.
            state.list.push(task);
        },
        // The deleteTodo reducer deletes a todo item from the list.
        deleteTodo: (state: any, action: any) => {
            // We have to write the logic yet
        }
    }
})

// Export the action creators for the slice, which are functions that create actions that can be dispatched to the Redux store.
// The action creators are generated by the createSlice function and are contained in the actions property of the slice.
export const { addTodo } = Slice.actions;

// Export the reducer for the slice, which is a function that takes the current state and an action, and returns a new state.
// The reducer is generated by the createSlice function and is contained in the reducer property of the slice.
export default Slice.reducer;